# Определение версии Docker Compose и начало описания сервисов
version: '3.9'

services:
  pgdb:
    # Использование готового образа postgres
    image: postgres:15.2
    # Задание переменных окружения для контейнера с postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${SQL_DB_NAME}
      POSTGRES_USER: ${SQL_DB_USER}
      POSTGRES_PASSWORD: ${SQL_DB_PASSWORD}
    restart: always
     # Задание имени контейнера для сервиса pgdb
    container_name: pgdb
     # Связывание тома с директорией в контейнере для сохранения данных postgres
    volumes:
      - pgdb_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${SQL_DB_USER} -d ${SQL_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 15

  api:
#    build: .
    image: sergdef/todolist_skypro:${GITHUB_REF_NAME}-${GITHUB_RUN_ID}
    container_name: api
    command: gunicorn todolist.wsgi:application --bind 0.0.0.0:8000
    env_file: .env.test
    environment:
      SQL_DB_HOST: pgdb
      SQL_DB_PORT: 5432
      SQL_DB_NAME: ${SQL_DB_NAME}
      SQL_DB_USER: ${SQL_DB_USER}
      SQL_DB_PASSWORD: ${SQL_DB_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      DEBUG: ${DEBUG}
      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_SECRET}
    restart: always
    depends_on:
      pgdb:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - django_static:/usr/src/app/django_static

  frontend:
    image: sermalenk/skypro-front:lesson-37
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      # путь на удаленном сервере nginx.conf
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # путь на локальной машине nginx.conf
#      - ./deploy_nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/django_static

volumes:
  pgdb_data:
  django_static:
